server:
  port: 8072

spring:
  application:
    name: scclient-consumer-hystrix

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8090/eureka/
feign:
  hystrix:    #feign中已经包含了hystirx，但是默认是不开启的，要手工打开
    enabled: true