server:
  port: 8090

eureka:
  instance:
    hostname: localhost
  client:
    #通过设置fetch-registry与register-with-eureka 表明自己是一个eureka服务
    fetch-registry: false       #是否从Eureka中获取注册信息
    register-with-eureka: false #是否将自己注册到Eureka服务中,本身就是所有无需注册
    service-url:                #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
security:
  basic:
    enable: false # 开启basic认证

spring:
  application:
    name: springcloudeurekaserver